### ISSUE TITLE
Permission denied 

### ISSUE THREAD

**Issue by supamongkonR** [gist-rs/book#9]
Hi P'@katopz , I've got a problem that I can't push new branch name solana(content in solana page) to create merge request and review before merge to main, and I gonna assign to P'@katopz as reviewer and merge it krub. 🥺🙏🏻

I've use SSH with new key generate also HTTPS too but it's still can't push krub, that why i think it come from permission on repo

it's seem like i don't have permission for this book repo krub 🥺

or I need to fork first and create merge request from my fork repo krub ? 🥺
```sh
ERROR: Permission to gist-rs/book.git denied to supamongkonR.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
```

```sh
remote: Permission to gist-rs/book.git denied to supamongkonR.
fatal: unable to access 'https://github.com/gist-rs/book.git/': The requested URL returned error: 403
``` 

This is content that I've to gonna push from my local repo krub.
<img width="1279" alt="image" src="https://github.com/gist-rs/book/assets/73258014/cba99778-fa9e-42bd-80a5-6e4d93e8fa3d">

🥺🥺🙏🏻

**Comment by supamongkonR** [comment]
OK krub now I can create merge request by fork fist 😅😅 this issue is closed krub.

**Comment by katopz** [comment]
1. Yes, you have to fork and make a PR for review.
2. Better create new branch (e.g. `consensus` or `dev`) instead of `main` on your repos because you will end up to rebase (and get mess up) when `original` has been changed and that will lead to code `conflict` later. see: [https://opensource.com/article/19/7/create-pull-request-github](https://opensource.com/article/19/7/create-pull-request-github)

HTH 🤗

**Comment by supamongkonR** [comment]
@katopz Thanks you so much krub, now I've create PR and waiting to review krub.

P'@katopz krub, Solana is so progressive!!! make us feel like living in a future, i never seen consensus like this before, 
they system design, how they make it fast. it so geniusssss!!!!

I've spent all my holiday all day all night with fun and feeling good when know more about this technology, 

I'll rise more content about solana and rust research krub. Thanks you so much again to help me and bring me to this world krub🥺🙏🏻
